### ISSUE TITLE
Login Issue 

### ISSUE THREAD

**Issue by ms3056** [thesamim/TickTickSync#135] opened 2024-05-26 23:55 UTC
I am geting an error on login - I have logged out on the web, logged in, delete the plugin, restarted Obsidian, restarted the plugin, etc. I am in a lockout state since last night. 

Maybe this will resolve, but I wanted to make you aware in case it is a API or plugin issue. 

![image](https://github.com/thesamim/TickTickSync/assets/23712700/6de4caaa-0c5e-49fb-8d85-80adfa608061)

**Comment by joseluizmm** [comment] 2024-05-27 17:01
same issue here
![image](https://github.com/thesamim/TickTickSync/assets/142648125/1e1ee497-8710-467d-bafd-11bd923cab12)

**Comment by franka107** [comment] 2024-05-28 14:23
Same

**Comment by thesamim** [comment] 2024-05-29 01:56
@ms3056 , @franka107 , @joseluizmm : That error code happens when TickTick returns no error code but returns no response body. In the past this has resolved itself in 24 hours. 

If it's been longer than that, please let me know.

Need to know: Is this the first time y'all are logging into TickTick from TickTickSync?

**Comment by franka107** [comment] 2024-05-29 05:53
Yes, it is my first time using TickTickSync. It has been approximately 48 hours since that error appeared. I just tried it today, and the error still persists
<img width="1245" alt="image" src="https://github.com/thesamim/TickTickSync/assets/49798546/2e98a6e1-21be-448b-89ef-b1a0ed265423">

**Comment by ms3056** [comment] 2024-05-29 08:59
For me it was the first time after uninstalling. I was getting too many tasks showing up for some reason and then I was getting an error in console - something about a ''<' character incorrect or something (sorry, I didn't capture it, because I thought it was my fault as I had some tasks that were - [>] and so on). 

I then uninstalled TickTickSync. I restarted Obsidian. I installed the plugin, entered my credentials, and now for 3+ days I am getting that error over and over again. 

Just tried again, now just to be sure

![image](https://github.com/thesamim/TickTickSync/assets/23712700/55b2e603-d9d5-450c-b3d4-257b521016cb)

**Comment by thesamim** [comment] 2024-05-29 15:32
@ms3056 , @franka107 , @franka107 , @joseluizmm , @dem0ngo: 
I will be debugging this.

Please turn on Debug Mode so we can get logs while this is happening.

In the meantime: Please add a new task in TickTick (preferably from the web) and give it a tag of #TestTickTickSync, then try logging in again. Let me know what happens. Thanks.

**Comment by dem0ngo** [comment] 2024-05-29 15:37
![image](https://github.com/thesamim/TickTickSync/assets/59857002/2bd513e3-3f69-4600-8de0-2a82abe9ce7f)

**Comment by thesamim** [comment] 2024-05-29 15:45
Thanks for the additional information.

Good news: I've found a way to reproduce the error.
Bad news;  I have no idea what's going on. 

Stand by for updates.

**Comment by thesamim** [comment] 2024-05-29 21:54
@ms3056 , @franka107 , @dem0ngo , @joseluizmm : Thanks for the bug report and your patience. 

Please try https://github.com/thesamim/TickTickSync/releases/tag/1.0.31

The issues:

1. TickTickSync has changed the way the process Checkpoint. Again.
2. The error message returned was HTML, not JSON

Both issues taken care of.

I will not close this issue until y'all confirm it's fixed.

**Comment by dem0ngo** [comment] 2024-05-29 23:26
That worked, thanks for fixing it so quickly!

**Comment by ms3056** [comment] 2024-05-30 01:42
Thank you SO MUCH. Your plugin is a critical part of my workflow. I appreciate the quick turnaround and the hard work you put in keeping up with the TickTick API changes. Thank you so much.

**Closed** 2024-05-30 01:41 UTC

**Comment by thesamim** [comment] 2024-05-30 14:58
All: 

Thanks for the feedback and your support!
