### ISSUE TITLE
Sync broken today

### ISSUE THREAD

**Issue by LemurTech** [thesamim/TickTickSync#82] opened 2024-03-15 16:56 UTC
Console error:

`plugin:tickticksync:23352 An error occurred: Error: EISDIR: illegal operation on a directory, read
scheduledSynchronization	@	plugin:tickticksync:23352
await in scheduledSynchronization (async)		
eval	@	plugin:tickticksync:13199
(anonymous)	@	app.js:1`

Project dropdowns have a 'load fail' in the list.

**Comment by thesamim** [comment] 2024-03-15 21:33
Before we get started:
1. What version are you on?
2. What platform are you on?
3. Is it possible the vault is opened in multiple instances of Obsidian? (ie: on desktop and on mobile simultaneously.)

The error could be caused by one of:
1. Error communicating with TickTick.com (There were would be a failure message sometime before the exception.)
2. An error with the directory that your vault is stored in. (not as likely.)


Please try:
1. Closing all instances of Obsidian that have access
2. Logging in again in just one instance of Obsidian. Let me know what error messages you see if any
4. Forcing a sync
5. If the error occurs again, please let me have the whole console log.

**Comment by LemurTech** [comment] 2024-03-15 22:50
I am on Windows, and no other instances are currently open. Obsidian version is 1.5.8 and TickTickSync is 1.0.18. I am able to login with username and password. After forcing a sync, it completes successfully, but console shows:

![image](https://github.com/thesamim/TickTickSync/assets/3136325/172747e2-29af-4406-acb4-28343f85805f)
[obsidian.md-1710542941292.log](https://github.com/thesamim/TickTickSync/files/14621431/obsidian.md-1710542941292.log)

**Comment by thesamim** [comment] 2024-03-15 23:05
I don't think it will make a difference but could you please upgrade to 1.0.19?

I **believe** what may be happening is that you had a file or folder at one point that has been deleted. Could you please check your data.json file to see if there is a stray file or folder?

**Comment by LemurTech** [comment] 2024-03-16 00:13
I couldn't identify any odd file or folder. I've tried a few things now, after backing up my TickTick tasks:

1. Resetting tasks and metadata as you have previously directed.
2. Nuking my data.json and going through the whole process again.

In either case, my login is accepted and sync reports "completed". But there's no change. I still get this:
![image](https://github.com/thesamim/TickTickSync/assets/3136325/71e2a91f-5b07-474d-b5ab-41bb9a713863)

**Comment by zarb1n** [comment] 2024-03-16 06:51
Hello,

I seem to be encountering a similar issue. While tasks created in Obsidian synchronize seamlessly with TickTick, I'm facing challenges with tasks initiated or modified within TickTick not reflecting any changes in Obsidian. Specifically, new tasks fail to synchronize, tasks originated in Obsidian and completed in TickTick remain unchanged in Obsidian, and so forth.

Additionally, when attempting to select a project for restricted syncing options, I encounter a "load fail" option alongside the free options. Choosing the second option results in a notification indicating that I "don't have a default file project for undefined."

I've attempted to troubleshoot this issue by creating a new vault and using a different TickTick account, but unfortunately, I've encountered the same behavior with the addon.

To gain further insight, I've enabled debug mode. After each synchronization attempt, the addon throws an error message stating `TypeError: Cannot read properties of null (reading 'path')`, or simply reports "We have: 0 tasks on https://api.ticktick.com/api/v2".

I encountered with it on addon's versions 18 and 19 yesterday about 10 UTC. I am not sure, but looks like there is a problem with TickTick API.

**Comment by thesamim** [comment] 2024-03-16 13:57
@LemurTech @zarb1n : What I suspect is happening is that there was a network problem communicating with TickTick. BUT: that should not have caused these failures. 

In order for me to further debug the failure points, could you please attach your data.json files here? What I'm specifically looking for is in the "projects": section:
1. Are the projects an accurate reflection of your lists in Ticktick?
2. Did you by any chance end up with a "Load Failed" project? (which would indicate a problem with the initial project load)
3. Do you have an "Inbox" project and does it have a non-null ID?
4. Do you have a list called "Inbox"? 

Of course, if there's any sensitive or proprietary data in data.json, please delete it first. 

Thanks.

**Comment by LemurTech** [comment] 2024-03-16 19:39
So glad to hear it, @thesamim ! Indeed, it seemed from the start like a sneaky API change. Thank you for this plugin!

**Closed** 2024-03-17 01:17 UTC

**Comment by thesamim** [comment] 2024-03-17 01:20
@LemurTech , @zarb1n : Thanks for your help!

Could you please re-test with 1.0.20

**Comment by LemurTech** [comment] 2024-03-17 01:32
Wonderful! Seems to be working again... Thanks so much for the prompt fix!

**Comment by thesamim** [comment] 2024-03-17 02:09
Glad to hear it. Most welcome.

**Comment by LemurTech** [comment] 2024-03-19 17:35
Sadly, having issues again. Console shows this again:

_An error occurred: Error: EISDIR: illegal operation on a directory, read_

I don't see any obvious issues in the configuration. Inbox is there, has an ID. No 'load fail' in projects menu.

```
  "enableFullVaultSync": false,
  "statistics": {},
  "debugMode": true,
  "TickTickTasksFilePath": "Task Sync",
  "inboxName": "Inbox",
  "inboxID": "inbox122919464",
  "SyncProject": "65d7ae4b8f0863df68630fbd",
  "SyncTag": "",
  "syncLock": false,
  "version": "1.0.20"
```
I tried a task rebuild. Sync says it completed, but it doesn't actually happen (project/task note is not populated).

**Comment by thesamim** [comment] 2024-03-19 18:24
I'm assuming that you can create a note in "Task Sync" from Obsidian?

Please paste the following in your console and hit enter:
```
const file = '/Tasks Sync';

// Check if the file exists in the current directory.
fs.access(file, fs.constants.F_OK, (err) => {
  console.log(`${file} ${err ? 'does not exist' : 'exists'}`);
});

// Check if the file is readable.
fs.access(file, fs.constants.R_OK, (err) => {
  console.log(`${file} ${err ? 'is not readable' : 'is readable'}`);
});

// Check if the file is writable.
fs.access(file, fs.constants.W_OK, (err) => {
  console.log(`${file} ${err ? 'is not writable' : 'is writable'}`);
});

// Check if the file is readable and writable.
fs.access(file, fs.constants.R_OK | fs.constants.W_OK, (err) => {
  console.log(`${file} ${err ? 'is not' : 'is'} readable and writable`);
});
```

This is what it looks like in my set up:
![image](https://github.com/thesamim/TickTickSync/assets/5315625/632ad5f2-aa00-43fa-b937-6aa554111517)

**Comment by LemurTech** [comment] 2024-03-19 19:29
Yes, the note *is* created in 'Task Sync', with TickTickSync's version entry at top.

Your console query nets me an error (I adjusted the '/Task Sync' directory name to match mine):

![image](https://github.com/thesamim/TickTickSync/assets/3136325/579babaa-ae0d-4618-89c7-bf0fea0ec362)

**Comment by LemurTech** [comment] 2024-03-19 19:35
I had more luck with this revision to the javascript:

```
const fs = require('fs').promises;

const path = 'Task Sync/'; 

async function checkAccess() {
  try {
    await fs.access(path, fs.constants.F_OK);
    console.log(`${path} exists`);
    
    await fs.access(path, fs.constants.R_OK);
    console.log(`${path} is readable`);
    
    await fs.access(path, fs.constants.W_OK);
    console.log(`${path} is writable`);
    
    await fs.access(path, fs.constants.R_OK | fs.constants.W_OK);
    console.log(`${path} is readable and writable`);
  } catch (err) {
    console.log(`${path} ${err.code === 'ENOENT' ? 'does not exist' : 'access error: ' + err.message}`);
  }
}

checkAccess();
```

![image](https://github.com/thesamim/TickTickSync/assets/3136325/4da6e8f8-6086-4296-8bc1-cdde8d17b002)

I don't know what's going on here, as the directory clearly exists.

**Comment by thesamim** [comment] 2024-03-19 21:23
That is very confusing. If Obsidian has access, TickTickSync should too.  

The error on the other computer is even more confusing: It indicates that at some point, the file existed (and is in your data.json in filemetadata), but now is now readable by Obsidian.

Is the directory on something like OneDrive or Google Drive? 
Is the directory a symbolic link or a Junction?
Does the directory have any special access permissions?

**Comment by LemurTech** [comment] 2024-03-19 22:19
Yeah, it gets even more confusing. Your file-access query is working now, but it still fails to detect the folder:

![image](https://github.com/thesamim/TickTickSync/assets/3136325/fb3f5719-5666-4034-aec3-418448352d54)

Here's the folder in my 'Public' vault on the D drive:

![image](https://github.com/thesamim/TickTickSync/assets/3136325/64e8d90b-3808-4531-a8fb-197947adb967)

It's not in a Google/OneDrive/DropBox and it's not a symbolic link; just a regular ol' directory. Could TickTick be mucking with their API again?

**Comment by LemurTech** [comment] 2024-03-19 22:29
Honestly, I think it hasn't been working since after that initial success the other day. It just ocurred to me to test it this morning, since I changed a due date in TickTick and didn't see it reflected in Obsidian. Then I did a manual sync to make sure and fell down this rabbit hole. :(

**Comment by thesamim** [comment] 2024-03-19 22:30
> It's not in a Google/OneDrive/DropBox and it's not a symbolic link; just a regular ol' directory. Could TickTick be mucking with their API again?

No, the error is local. The failure point, in the code, is on accessing a file or folder after the tasks have been downloaded. 

Could you please execute (adjusting for your folder, file names), from non-admin powershell cmd line:

```
Get-Item 'E:\Dev\testVault\Tasks Sync\' | Format-List
Get-Item 'E:\Dev\testVault\Tasks Sync\From here.md' | Format-List
```

**Comment by LemurTech** [comment] 2024-03-19 23:02
Here you are. Seems to be fine:

```
PS U:\> Get-Item 'D:\Obsidian\Public\Task Sync\' | Format-List                                                          

    Directory: D:\Obsidian\Public

Name           : Task Sync
CreationTime   : 3/19/2024 9:04:00 AM
LastWriteTime  : 3/19/2024 3:48:36 PM
LastAccessTime : 3/19/2024 3:58:09 PM
Mode           : d-----
LinkType       :
Target         : {D:\Obsidian\Public\Task Sync}

PS U:\> Get-Item 'D:\Obsidian\Public\Task Sync\Work.md' | Format-List

    Directory: D:\Obsidian\Public\Task Sync

Name           : Work.md
Length         : 38
CreationTime   : 3/19/2024 12:52:12 PM
LastWriteTime  : 3/19/2024 12:52:13 PM
LastAccessTime : 3/19/2024 3:58:09 PM
Mode           : -a----
LinkType       :
Target         : {}
VersionInfo    : File:             D:\Obsidian\Public\Task Sync\Work.md
                 InternalName:
                 OriginalFilename:
                 FileVersion:
                 FileDescription:
                 Product:
                 ProductVersion:
                 Debug:            False
                 Patched:          False
                 PreRelease:       False
                 PrivateBuild:     False
                 SpecialBuild:     False
                 Language:
```

**Comment by thesamim** [comment] 2024-03-19 23:18
yup, all looks good.

What's your vault's root directory? is it `D:\Obsidian` or `D:\Obsidian\Public` ?

**Comment by LemurTech** [comment] 2024-03-19 23:20
`D:\Obsidian\Public` is my 'Public' vault root.

**Comment by thesamim** [comment] 2024-03-19 23:38
in your log, there should be a line that looks like this: 
`We have:  0  tasks on https://api.ticktick.com/api/v2`

What's the number of tasks showing?

**Comment by LemurTech** [comment] 2024-03-19 23:42
I don't even get that far now:

![image](https://github.com/thesamim/TickTickSync/assets/3136325/c21e481e-d450-4cad-abf4-5ae602f7e5d8)

**Comment by LemurTech** [comment] 2024-03-19 23:54
Something here that seems odd, but may be nothing:

Default Project menu looks like this, with 2 'Work' projects.
![image](https://github.com/thesamim/TickTickSync/assets/3136325/cb720e8b-571b-4b3e-85ed-5f9612681d11)

Project folder just has the one:
![image](https://github.com/thesamim/TickTickSync/assets/3136325/4c7454bf-d7ea-4ccd-a440-5a0e4ab6e272)

**Comment by LemurTech** [comment] 2024-03-20 00:10
FYI, I tried switching the Default project to something else, such as "Inbox". The new file was created at the folder location just fine, but it eventually resulted in the same error suggesting that the plugin can't 'see' the file. I wondered if there could be some other community plugin interfering somehow. I made sure to add my "Task Sync" folder to any and all exclusion lists for plugins like Linter and Metadata Menu. I also tried resetting NTFS permissions on the folder to make sure my user had full control. Nothing has made a difference, so far.

**Comment by thesamim** [comment] 2024-03-20 13:18
> Issue happens on 3 different PCs and an Android device--all with same symptoms (though I haven less visibility into the Android).

Is the same vault directory shared across the three different PC's? If so: it's possible that the issue that the default file is opened in one instance of Obsidian, while the other instance is checking... BUT that doesn't explain any of the other symptoms (as in: the next sync should be able to check the file...)

What does your filemetadata entry in data.json look like on all three PCs?

BTW: If you want to check Android logs, you can either use the "logstravaganza" plugin or follow instructions here: https://developer.chrome.com/docs/devtools/remote-debugging

If you're interested in validating that the plugin actually works on one of the three PCs, I would recommend starting a new vault, in a directory that is not accessed by any other application or Obsidian instance. Only install the Tasks and TickTickSync plugins. Do several synchronizations. That would tell us if there's something going on with TickTick itself, or if there's a definite TickTickSync issue.

If a different vault, with no competing access works, then we can start considering how to mitigate situations where multiple instances are accessing the same vault.... (there's already some mitigation in that TickTickSync checks " "syncLock": false,"  in data.json before performing any updates. But it may be that I need to expand that check for read access as well....

**Comment by zarb1n** [comment] 2024-03-20 14:00
Hey there,

You will laugh, but I am encountered with the similar problem again:
1. Tasks from TickTick aren't syncing;
2. Error `An error occurred: TypeError: Cannot read properties of null (reading 'path')` raised in the console;
3. There were two the same options in dropdown with projects (FYI I use limited sync only by tag) -- after relogin this dissapeared.

Also I tested it on another vault with another TickTick account: tasks still aren't syncing, but here addont doesn't throw the error -- just log "We have:  0  tasks on https://api.ticktick.com/api/v2".

**Comment by thesamim** [comment] 2024-03-20 14:02
> You will laugh, but I am encountered with the similar problem again:

I will not laugh. I may cry.

I'm looking into it.

**Comment by zarb1n** [comment] 2024-03-20 14:06
> I will not laugh. I may cry.

I'm really sorry.( You develop a very cool unique product. If you need any help with testing, I am ready to help.

**Comment by LemurTech** [comment] 2024-03-20 14:22
I'm so glad it's not just me! I was feeling lonely!

On Android, the plug-in actually does see a number of tasks, unlike the desktop. But then it encounters an error, which it does not output in the log here.

![SmartSelect_20240320_071747_Obsidian](https://github.com/thesamim/TickTickSync/assets/3136325/07cf9d5e-b2b4-43e2-b936-60ad84540f70)

**Comment by thesamim** [comment] 2024-03-20 14:48
@LemurTech , @zarb1n : 
UPDATE: 
I can reproduce the problem in some vaults, but not in other vaults. Which doesn't make sense.

What I'm surprised about: you two are the only ones reporting the issue. I would have expected a whole bunch of people running into this....

I'm working on it...

Thanks for your patience!

**Comment by zarb1n** [comment] 2024-03-20 15:33
> you two are the only ones reporting the issue. I would have expected a whole bunch of people running into this

We are the luckiest, perhaps.)

Thanks! I'm looking forward to it!

**Comment by thesamim** [comment] 2024-03-20 19:26
@LemurTech , @zarb1n : Could y'all please save main.js in `<vault root>\.obsidian\plugins\TickTickSync` and replace it with the attached main.js?
[TickTickSync-TEST-1.0.21.zip](https://github.com/thesamim/TickTickSync/files/14671500/TickTickSync-TEST-1.0.21.zip)

This should take care of not fetching tasks correctly. 

In case you're interested: 

- the end point `(https://api.ticktick.com/api/v2/batch/check/` which is used to get all tasks takes a numeric parameter. 
- Before, `https://api.ticktick.com/api/v2/batch/check/0` returned all tasks. 
- But now it doesn't. I *assumed* that the numeric parameter was just an index. It's not. It's a checkpoint numeric. As in: behind the scenes, TickTick is comparing the last checkpoint fetched to the current checkpoint requested. 
- So, the 0 and 1 worked correctly before, but it doesn't now. 
- So the quick fix is to increment the numeric parameter until we get correct results. 

The real fix will be to verify my findings and actually use the checkpoint logic (as in: capture the first checkpoint and fetch incremental checkpoints after). BUT: I'm not convinced that TickTick is returning the correct tasks per checkpoint fetch. IF it does work correctly, it might save a ton of processing, but I'd have to adjust the logic because it currently assumes that ALL tasks are fetched, not some subset.... I'll put that on the roadmap...

@LemurTech :  I don't think any of this is going to fix the issue with "An error occurred: Error: EISDIR: illegal operation on a directory, read". If that happens again, please open a new issue so we can figure out what's going on without the extraneous noise of the API failing.....

**Comment by LemurTech** [comment] 2024-03-20 20:39
@thesamim - Well, it's interesting. Replacing that file and syncing immediately brought my tasks in from TickTick. But watching the console, I saw this:

![image](https://github.com/thesamim/TickTickSync/assets/3136325/7e2910e0-8980-4d0d-af29-d4e70f3ac8fe)

I then tried some experiments around changing due dates in both TickTick and Obsidian to see if they would sync.

At the very first, it seemed I could make changes in TickTick and those would sync down, whereas the reverse would not work. But then things quickly got weird again, and that "EISDIR" error appeared. I would change a due date in TickTick, sync, and the TickTick task would revert to what the Obsidian task was showing. Or I would change the due date in Obsidian, sync, and the TickTick task would not change. Or I could change both, sync, and the Obsidian task would stay the same, but the TickTick task would revert to what it had been previously, but NOT what Obsidian was showing.

I am going to try this on a different PC to see if the findings are equally strange there.

**Comment by LemurTech** [comment] 2024-03-20 21:45
Ok, I've got things working on both my work and home PC, with no errors showing on either. When last I wrote, I was on my work PC. Here's what I did:

1. Closed Obsidian on work PC
2. Opened Obsidin on home PC. Waited for Obsidian Sync to finish, reloaded plugins, ran TickTickSync. It failed.
3. Reset data.json Tasks and Metadata, per earlier instructions.
4. Ran the sync. IT WORKED. Tried various things: change due date on TickTick, change due date in Obsidian. All changes synced with no errors. Closed Obsidian, opened again, still good.
5. Tried on my Android: wait for Obsidian Sync, reload plugins. It failed. Logstravaganza shows some error, but doesn't say what kind. 
6. Closed Android, tried again on home PC. Still good there: zero errors, and changes sync.
7. Closed Obsidian on home PC, opened it on work PC. Waiting for Obsidian Sync. Everything works with TickTickSync, zero errors.

Aside from Android failing to sync, only noticeable issue was that TickTickSync used to trigger an update to TickTick immediately upon a task change; that is no longer happening. I'm at a loss to explain what's happening in all of this. If I had to guess I'd say that my data.json had gotten corrupted somehow, and when I reset the tasks and metadata on my home PC, it cleared the issue.

I realize this is complicated by the issue of me syncing several different devices. I'd doing my best to isolate the issue, but it's also just how I have to work on several different machines. Thanks for all your work on this!

**Comment by thesamim** [comment] 2024-03-20 21:57
What are you using to sync the various devices?

**Comment by LemurTech** [comment] 2024-03-20 22:59
I am using Obsidian's native sync product. Because of the number of small changes I'm making to files, I invevitably have to wait for the sync to finish before I dare to use any of my notes or touchy plugins.

TickTickSync is still working on my work PC, though this error has now popped up:
![image](https://github.com/thesamim/TickTickSync/assets/3136325/cd734aa0-29a2-4817-9df9-f7ce94d821ba)

Yes, I DO see an 'undefined':
```
    "undefined": {
      "TickTickTasks": [],
      "TickTickCount": 0
    },

```

**Comment by thesamim** [comment] 2024-03-21 05:13
I'll find out how that got there eventually. For now, it's safe to delete that entry.

**Comment by LemurTech** [comment] 2024-03-21 05:42
I tried deleting it, and it just comes right back.

**Comment by zarb1n** [comment] 2024-03-21 05:57
Hey!

After taking some actions, such as removing the "undefined" object, utilizing version 21 of main.js, and possibly making some adjustments in the UI, my entire Obsidian vault began behaving strangely. It reindexed itself, logged out from remote vault sync, and threw numerous errors from both Obsidian Core and the Dataview plugin. While I can't confirm direct causation, this information might prove useful.

Unfortunately, despite these changes, tasks still aren't syncing correctly. Moreover, the addon is now altering timestamps and reopening previously removed or completed tasks in TickTick. As a temporary solution, I've disabled the plugin in my main vault and will attempt to restore Obsidian's functionality. Now will try reproduce some bugs into my test vault and TT-account.

As for the issue with "undefined," I'm uncertain about its origin. However, it might be somehow linked to selecting a project in limited synchronization. When clicking on the empty list option, the addon indicates that it "did not find a default project file for Project undefined" via obsidian notification.

**Comment by LemurTech** [comment] 2024-03-21 17:00
> I tried deleting it, and it just comes right back.

My bad. File was locked. It's working now. So far, so good, today!

**Comment by thesamim** [comment] 2024-03-21 17:40
@LemurTech , @zarb1n : 

**Thanks so much for all your help.** 

Please see the acknowledgement section of the [readme file](https://github.com/thesamim/TickTickSync/blob/1.0.21/README.md) :)

I know there's still issues with file/directories being locked during synchronizations. [IMXeno123](https://github.com/IMXeno123) just opened #86 and I will work on it under that issue. Please feel free to add additional information there.

**Comment by zarb1n** [comment] 2024-03-22 06:40
Thank you a lot for your amazing work and continued support!
